version: '3.8'

services:
  mongodb:
    image: mongo:5.0
    container_name: mongodb
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: ${MONGO_INITDB_USERNAME}
      MONGO_INITDB_ROOT_PASSWORD: ${MONGO_INITDB_PASSWORD}
    networks:
      - secret_network
    volumes:
      - mongo_data:/data/db
    expose:
      - ${MONGO_DB_PORT}

  secret_manager:
    build: ./secret_manager  
    container_name: secret_manager
    restart: always
    environment:
      MONGO_URI: ${MONGO_URI}
    networks:
      - secret_network
    depends_on:
      - mongodb

networks:
  secret_network:
    driver: bridge
volumes:
  mongo_data:
    driver: local
