version: '3.8'

services:
  mongodb:
    image: mongo:5.0
    container_name: mongodb
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: ${MONGO_INITDB_USERNAME}
      MONGO_INITDB_ROOT_PASSWORD: ${MONGO_INITDB_PASSWORD}
    networks:
      - secret_network
    volumes:
      - mongo_data:/data/db
    expose:
      - ${MONGO_DB_PORT}

  postgres:
    image: postgres:13
    container_name: postgres
    restart: always
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - secret_network


  secret_manager:
    build: .
    container_name: secret_manager
    restart: always
    environment:
      POSTGRES_URI: ${POSTGRES_URI}
      MONGO_URI: ${MONGO_URI}
    ports:
      - "8000:8000"
    depends_on:
      - mongodb
      - postgres
    networks:
      - secret_network
    
    volumes:
      - ./alembic/versions:/app/alembic/versions
      - ./wait-for-it.sh:/wait-for-it.sh
      - .:/app


networks:
  secret_network:
    driver: bridge
volumes:
  mongo_data:
    driver: local
  postgres_data:
    driver: local
