version: '3.8'

services:
  mongodb:
    image: mongo:5.0
    container_name: mongodb
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: ${SECRET_DB_USERNAME}
      MONGO_INITDB_ROOT_PASSWORD: ${SECRET_DB_PASSWORD}
    networks:
      - secret_network
    volumes:
      - mongo_data:/data/db
    expose:
      - ${SECRET_DB_PORT}

  mongodb_auth:
    image: mongo:5.0
    container_name: mongodb_auth
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: ${MONGO_AUTH_INITDB_USERNAME}
      MONGO_INITDB_ROOT_PASSWORD: ${MONGO_AUTH_INITDB_PASSWORD}
    networks:
      - secret_network
    volumes:
      - mongo_auth_data:/data/db
    expose:
      - ${MONGO_AUTH_DB_PORT}

  secret_manager:
    build: .
    container_name: secret_manager
    restart: always
    environment:
      MONGO_AUTH_DB_URI: ${MONGO_AUTH_URI}
      SECRET_DB_URI: ${SECRET_DB_URI}
    ports:
      - "8000:8000"
    depends_on:
      - mongodb
      - mongodb_auth
    networks:
      - secret_network

    volumes:
      - ./alembic/versions:/app/alembic/versions

networks:
  secret_network:
    driver: bridge
volumes:
  mongo_data:
    driver: local
  mongo_auth_data:
    driver: local
